/**
 * Precision guard: keeps the list of coarse coordinates from growing silently.
 *
 * ## Why a lock (baseline) and not "zero allowed"
 *
 * 68 point-places in the catalog are already coarse (≤2 decimal digits, ~1.1km
 * error or worse) - existing data debt, not a code bug. Blocking every commit
 * until it drops to zero would stop all unrelated work, exactly what the
 * documentation of `coarse-coords.mjs` warns against. But "don't block" is not
 * the same as "don't watch" - whoever asked for this test was explicit: "I don't
 * want this to regress backwards". The solution: the current list must be a
 * **subset** of the list locked here. A new coarse place (or an old place that
 * worsened from area to point) fails immediately and by name; a place that was
 * fixed simply disappears from the list, without updating a test.
 *
 * ## Why only 'point'
 *
 * An area (national park, lake) with a coarse center is distinctly legitimate -
 * see the documentation in `coordPrecision.ts`. This baseline tracks only the
 * case that actually hurts.
 *
 * ## How to update the baseline deliberately
 *
 * Fixed a place? It disappears from the list on its own - no update needed
 * here. Added a place *with a precise coordinate* and got a failure by mistake?
 * Should not happen - the check only detects coarseness, not ISO-anything. The
 * only real failure that should occur here is a new point-place with a coarse
 * coordinate, and then the fix is to correct the coordinate, not to add it to
 * the baseline.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { coarseCoordRows } from './coordPrecision.ts';
import { destinations } from '../data/destinations.ts';

/**
 * The locked baseline, as of 2026-08-12 (the Google Maps links audit) - 68
 * point-places. Generated by `coarse-coords.mjs --json` and filtered to shape='point'.
 */
const BASELINE_COARSE_POINT_IDS: readonly string[] = [
  'amman-north/amn-madaba',
  'athens/ath-plaka',
  'balaton/blt-balatonfured',
  'bergen-fjords/nor-bergen',
  'bratislava/bts-castle',
  'cape-town/zaf-robben',
  'cartagena/co-getsemani',
  'chisinau-moldova/md-cricova',
  'colca-titicaca/pe-chivay',
  'cultural-triangle/lk-polonnaruwa',
  'dalmatia-split/hr-diocletian',
  'dalmatia-split/hr-hvar',
  'dalmatia-split/hr-korcula',
  'dolomites/dol-bolzano',
  'douro/pt-foz-coa',
  'douro/pt-lamego',
  'dubai/dxb-bastakiya',
  'finnish-lapland/fla-rovaniemi',
  'garden-route/zaf-oudtshoorn',
  'gdansk-pomerania/pl-frombork',
  'gyeongju-busan/kr-bulguksa',
  'gyeongju-busan/kr-gyeongju',
  'gyeongju-busan/kr-jagalchi',
  'halong/vnm-chabad',
  'halong/vnm-hanoi',
  'interlaken/int-hoheweg',
  'kathmandu/npl-kathmandu',
  'kathmandu/npl-swayambhu',
  'lisbon/lis-alfama',
  'lycian-coast/tr-kas',
  'mostar-sarajevo/bih-bascarsija',
  'new-york/nyc-williamsburg',
  'north-iceland/is-husavik',
  'north-zealand/nzl-roskilde-cathedral',
  'northern-bulgaria/bg-tryavna',
  'panama-canal-bocas-boquete/pa-boquete',
  'penang-perak/my-taiping',
  'petra/pet-wadimusa',
  'phnom-penh-coast/kh-battambang',
  'plitvice/hrv-diocletian',
  'plitvice/hrv-split',
  'prague/prg-castle',
  'prague/prg-josefov',
  'quito-cotopaxi-andes/ec-quito',
  'quito-cotopaxi-andes/ecu-mercado-central',
  'riga/rga-sigulda',
  'rila-pirin/rlp-bansko',
  'rila-pirin/rlp-melnik',
  'salzburg/szg-oldtown',
  'santorini-mykonos/cyc-fira',
  'santorini-mykonos/cyc-mykonos-museum',
  'saxon-switzerland/sax-bad-schandau',
  'saxon-switzerland/sax-rathen',
  'sofia/sof-market-hall',
  'sofia/sof-synagogue',
  'south-albania/alb-saranda',
  'taiwan-island-loop/tw-beitou',
  'tasmania/au-port-arthur',
  'tbilisi/tbs-metekhi',
  'tbilisi/tbs-synagogue',
  'tian-shan-issyk-kul/kg-naryn',
  'valais-zermatt/ch-zermatt',
  'vienna/vie-bahur-tov',
  'vienna/vie-belvedere',
  'warsaw/war-barbican',
  'west-estonia-islands/ee-kuressaare',
  'west-ireland/irw-poulnabrone',
  'yerevan/arm-tatev',
];

test('רשימת המקומות-נקודה עם קואורדינטה גסה לא גדלה מעבר לבסיס הנעול', () => {
  const baseline = new Set(BASELINE_COARSE_POINT_IDS);
  const current = coarseCoordRows(destinations, 2).filter((r) => r.shape === 'point');

  const regressed = current.filter((r) => !baseline.has(`${r.destination}/${r.id}`));
  assert.deepEqual(
    regressed.map((r) => `${r.destination}/${r.id}  ${r.name}  (${r.lat},${r.lng})`),
    [],
    `${regressed.length} מקום/מקומות-נקודה חדשים עם קואורדינטה גסה (≤2 ספרות עשרוניות). ` +
      `זה כנראה מקום חדש שנוסף בלי קואורדינטת GPS אמיתית - יש לתקן את הדאטה, לא את הטסט.`,
  );

  // Living documentation: how much of the baseline is still actually coarse vs. fixed.
  // Does not fail on a decrease - a decrease is the progress this check exists to enable.
  const fixed = BASELINE_COARSE_POINT_IDS.length - current.filter((r) => baseline.has(`${r.destination}/${r.id}`)).length;
  if (fixed > 0) {
    console.log(`(${fixed} מקומות מהבסיס הנעול תוקנו מאז - כל הכבוד, אין צורך לעדכן את הטסט)`);
  }
});

test('שטחים (nature/viewpoint) לא נכנסים לבדיקת הגסות - זה לגיטימי עבורם', () => {
  const rows = coarseCoordRows(destinations, 2);
  const areaRows = rows.filter((r) => r.shape === 'area');
  assert.ok(areaRows.length > 0, 'הצפי הוא שיהיו כמה - זה מוודא שהסינון בכלל פעיל ולא שקוף');
  for (const r of areaRows) {
    assert.ok(
      r.category === 'nature' || r.category === 'viewpoint',
      `${r.destination}/${r.id} סווג כ-area אבל הקטגוריה שלו היא ${r.category}`,
    );
  }
});
