import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { getProvider } from '@/lib/providers';
import { destinations } from '@/data/destinations';
import { countries } from '@/data/countries';
import { canonical, metaDescription } from '@/lib/seo/site';
import { isSeoDestination } from '@/lib/seo/selection';
import { breadcrumbLd, faqLd, faqPairs, touristDestinationLd } from '@/lib/seo/jsonLd';
import JsonLd from '@/components/seo/JsonLd';
import DestinationGuide from '@/components/seo/DestinationGuide';
import DestinationClient from './DestinationClient';
import PhotoCredits from '@/components/PhotoCredits';
import { creditsFor, shareImage } from '@/lib/server/photoCredit';

export function generateStaticParams() {
  return destinations.map((d) => ({ slug: d.slug }));
}

/**
 * Per-destination metadata.
 *
 * ## The defect this fixes
 *
 * This page had no `generateMetadata` at all, so all 166 destinations served the
 * root layout's title and description verbatim - verified in the deployed HTML,
 * where `/destinations/vienna` came back carrying the generic site-wide title
 * ("tiyul+ | the smart travel agent for Israelis") rather than anything about
 * Vienna. 166 pages with an identical title and description are, to a search
 * engine, 166 near-duplicates competing with each other. There was also no
 * canonical tag anywhere on the site.
 *
 * ## Every field comes from the catalog
 *
 * The title is built from the city's own Hebrew name and its country, and the
 * description from the curated `tagline` and `summary`. No copy is written here
 * and nothing is generated by a model, at build time or at request time.
 *
 * All 166 get this, not just the 30 promoted ones: a shared title is a bug for
 * every page that has it, independent of which pages we are choosing to push.
 */
export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const dest = destinations.find((d) => d.slug === slug);
  if (!dest) return {};
  const country = countries.find((c) => c.slug === dest.countrySlug);

  const where = country ? `${dest.name}, ${country.name}` : dest.name;
  const title = `${where}: מה לעשות, כמה ימים ומסלול מוכן | טיול+`;
  const description = metaDescription(dest.tagline, dest.summary);
  const url = canonical(`/destinations/${dest.slug}`);
  // The destination's own hero photo where it has one (165 of 166 do), widened
  // to what the original really allows; otherwise the root layout's site-wide
  // og.png still applies. See `shareImage` for why the stored width is too small.
  const image = shareImage(dest.photo, `${dest.name} - ${dest.tagline}`);

  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: 'article',
      locale: 'he_IL',
      siteName: 'טיול+',
      url,
      title,
      description,
      ...(image ? { images: [image] } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      ...(image ? { images: [image] } : {}),
    },
  };
}

export default async function DestinationPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const provider = getProvider();
  const dest = await provider.getDestination(slug);
  if (!dest) notFound();
  const country = await provider.getCountry(dest.countrySlug);
  if (!country) notFound();
  const promoted = isSeoDestination(dest.slug);
  /*
    Breadcrumb and TouristDestination go on all 166 - every one of them is a
    real place with a curated description and verified coordinates, and the
    markup describes what the catalog page renders.

    FAQPage goes only on the promoted 30, and that is a correctness constraint
    rather than caution: structured data must describe what is on the page, and
    the answers it declares are the guide's own prose. On the other 136 that
    prose is not rendered, so the markup would be describing a page that does
    not exist.
  */
  const ld = [
    breadcrumbLd([
      { name: 'טיול+', path: '/' },
      { name: 'יעדים', path: '/countries' },
      { name: country.name, path: `/countries/${country.slug}` },
      { name: dest.name, path: `/destinations/${dest.slug}` },
    ]),
    touristDestinationLd(dest, country),
    ...(promoted ? [faqLd(faqPairs(dest, country))] : []),
  ].filter((n): n is NonNullable<typeof n> => Boolean(n));

  return (
    <>
      <JsonLd data={ld} />
      <DestinationClient dest={dest} country={country} />
      {/*
        The guide is appended below the interactive catalog UI, and only for the
        promoted destinations. Two deliberate choices:

        - **Below, not above.** The interactive map and filters are what a
          returning user came for; burying them under a wall of text to serve a
          crawler would trade a real user's experience for a ranking signal that
          does not depend on position anyway.
        - **Only the promoted 30.** The other 136 render exactly as before. See
          `@/lib/seo/selection` for why the set is small and pinned.
      */}
      {promoted && <DestinationGuide dest={dest} country={country} />}

      {/*
        Attribution for every photograph this page can show - the hero, the
        landmark card and each place - resolved on the server so the 828KB
        credit manifest never reaches the browser.

        It lists what the page CAN render rather than what happens to be
        visible after filtering, because the filters are client state and a
        credit that disappears when somebody clicks a chip is not attribution.
      */}
      <PhotoCredits
        credits={creditsFor([
          dest.photo,
          dest.iconicLandmark?.photo,
          ...dest.places.map((pl) => pl.photo),
        ])}
      />
    </>
  );
}
