import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { getProvider } from '@/lib/providers';
import { destinations } from '@/data/destinations';
import { countries } from '@/data/countries';
import { canonical, metaDescription } from '@/lib/seo/site';
import DestinationClient from './DestinationClient';

export function generateStaticParams() {
  return destinations.map((d) => ({ slug: d.slug }));
}

/**
 * Per-destination metadata.
 *
 * ## The defect this fixes
 *
 * This page had no `generateMetadata` at all, so all 166 destinations served the
 * root layout's title and description verbatim - verified in the deployed HTML,
 * where `/destinations/vienna` came back carrying the generic site-wide title
 * ("tiyul+ | the smart travel agent for Israelis") rather than anything about
 * Vienna. 166 pages with an identical title and description are, to a search
 * engine, 166 near-duplicates competing with each other. There was also no
 * canonical tag anywhere on the site.
 *
 * ## Every field comes from the catalog
 *
 * The title is built from the city's own Hebrew name and its country, and the
 * description from the curated `tagline` and `summary`. No copy is written here
 * and nothing is generated by a model, at build time or at request time.
 *
 * All 166 get this, not just the 30 promoted ones: a shared title is a bug for
 * every page that has it, independent of which pages we are choosing to push.
 */
export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const dest = destinations.find((d) => d.slug === slug);
  if (!dest) return {};
  const country = countries.find((c) => c.slug === dest.countrySlug);

  const where = country ? `${dest.name}, ${country.name}` : dest.name;
  const title = `${where}: מה לעשות, כמה ימים ומסלול מוכן | טיול+`;
  const description = metaDescription(dest.tagline, dest.summary);
  const url = canonical(`/destinations/${dest.slug}`);

  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: 'article',
      locale: 'he_IL',
      siteName: 'טיול+',
      url,
      title,
      description,
      // The destination's own hero photo where it has one (165 of 166 do);
      // otherwise the root layout's site-wide og.png still applies.
      ...(dest.photo
        ? { images: [{ url: dest.photo, alt: `${dest.name} - ${dest.tagline}` }] }
        : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      ...(dest.photo ? { images: [dest.photo] } : {}),
    },
  };
}

export default async function DestinationPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const provider = getProvider();
  const dest = await provider.getDestination(slug);
  if (!dest) notFound();
  const country = await provider.getCountry(dest.countrySlug);
  if (!country) notFound();
  return <DestinationClient dest={dest} country={country} />;
}
